"""Generate RESULTS.md from the pipeline's artifacts.

A judge browsing the repo should be able to see every number without cloning,
installing, or running anything. GitHub renders Markdown inline, so this is a
better hedge than an HTML file they would have to download.

Everything here is read from data/*.json. Nothing is typed in by hand, which
means the report cannot drift away from what the code actually produces --
the failure mode where a README quietly describes a version that no longer
exists.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "RESULTS.md"


def load(name: str) -> dict[str, Any] | None:
    path = DATA / name
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def main() -> int:
    d3, d4, d5, d6 = (load(f"day{n}_results.json") for n in (3, 4, 5, 6))
    missing = [n for n, d in zip((3, 4, 5, 6), (d3, d4, d5, d6), strict=True) if d is None]
    if missing:
        print(f"missing artifacts for day(s) {missing}; run the scripts first")
        return 1

    ate, m, pol = d3["ate"], d4["model"], d4["policies"]
    peek, det, frz = d3["peeking"], d5["detector"], d5["freeze"]
    b, a = d6["pnl"]["baseline"], d6["pnl"]["antar"]
    comp = d6["compliance"]
    adv = [p["advantage"] for p in d4["sweep"]]

    parts: list[str] = []
    w = parts.append

    w("# ANTAR — measured results\n")
    w("*Generated by `scripts/build_report.py` from the pipeline's own artifacts. "
      "Nothing here is typed in by hand, so it cannot drift from what the code "
      f"produces.*\n\nSeed `{d3['config']['seed']}` · "
      f"{d3['config']['n']:,} failed payments · every figure reproducible with "
      "`python scripts/run_day1.py` … `run_day6.py`.\n")

    w("---\n\n## 1. The claim\n")
    w("Recovery tools are scored on gross rupees recovered. That number is mostly "
      "money that was arriving anyway, and optimising for it drives the system "
      "toward the customers it helps least.\n")
    w(f"| | Baseline | ANTAR |\n|---|---:|---:|\n"
      f"| Headline claim | ₹{b['last_touch_claim']:,.0f} | ₹{a['last_touch_claim']:,.0f} |\n"
      f"| **Actually caused** | **₹{b['incremental_recovery']:,.0f}** | "
      f"**₹{a['incremental_recovery']:,.0f}** |\n"
      f"| Retention damage | ₹{b['retention_damage']:,.0f} | ₹{a['retention_damage']:,.0f} |\n"
      f"| **Net value created** | **₹{b['net_value']:,.0f}** | ₹{a['net_value']:,.0f} |\n"
      f"| Contacts sent | {b['contacts']:,} | {a['contacts']:,} |\n"
      f"| Headline overstates by | {b['overstatement']:.1f}× | {a['overstatement']:.1f}× |\n")
    w(f"ANTAR creates **{a['net_value'] / max(b['net_value'], 1e-9):.1f}× the net value on "
      f"{1 - a['contacts'] / max(b['contacts'], 1):.0%} fewer contacts.** Both policies run "
      "under identical compliance rules and the same incident freeze.\n")

    w("---\n\n## 2. The inversion\n")
    w("Effect by decline class, measured against a randomised control arm. `p1` is the "
      "treated recovery rate — the column a conventional tool optimises. `uplift` is the "
      "difference the control arm reveals.\n")
    w("| Class | Estimated effect | 95% confidence sequence | Ground truth | Verdict |\n"
      "|---|---:|:---:|---:|---|\n")
    for r in d3["by_class"]:
        verdict = "detected" if r["detected"] else "indistinguishable from zero"
        w(f"| `{r['class']}` | {r['point']:+.3f} | "
          f"[{r['lower']:+.3f}, {r['upper']:+.3f}] | {r['truth']:+.3f} | {verdict} |\n")
    w("\n**Transient rail failures cannot be distinguished from doing nothing** — and that "
      "is where the baseline spends most of its budget. Classes with wide intervals are "
      "not null; their control arms are too thin to resolve an effect that size. That is a "
      "power limitation, reported as one.\n")

    w("---\n\n## 3. Does the model recover an effect it never sees?\n")
    w(f"- `corr(predicted CATE, true uplift)` = **{m['recovery_corr']:+.3f}**\n"
      f"- True uplift in the predicted top decile: **{m['top_decile_true_uplift']:+.3f}**; "
      f"bottom decile: {m['bottom_decile_true_uplift']:+.3f}\n"
      f"- Qini — ANTAR **{m['qini_antar']:+.3f}**, baseline **{m['qini_naive']:+.3f}**\n")
    w("\nThe baseline's ranking is *worse than random* at finding incremental responders. "
      "Accuracy would never reveal that: a model can rank outcomes perfectly and uplift "
      "terribly, which is exactly what success-rate targeting does.\n")
    w(f"\nOn identical budgets, persuadables reached goes "
      f"{pol['baseline']['persuadable_share']:.1%} → **{pol['antar']['persuadable_share']:.1%}**, "
      f"and contacts that changed nothing {pol['baseline']['wasted_share']:.1%} → "
      f"**{pol['antar']['wasted_share']:.1%}**.\n")

    w("---\n\n## 4. Does it survive moving the assumption?\n")
    w("Self-recovery is the assumption everything rests on, so it is swept across its "
      "plausible range.\n\n")
    w("| Self-recovery scale | Mean p0 | Baseline (₹) | ANTAR (₹) | Advantage |\n"
      "|---:|---:|---:|---:|---:|\n")
    for p in d4["sweep"]:
        w(f"| {p['scale']:.2f} | {p['mean_p0']:.3f} | {p['baseline_inr']:,.0f} | "
          f"{p['antar_inr']:,.0f} | {p['advantage']:.2f}× |\n")
    w(f"\n**The magnitude does not survive** — at low self-recovery the policies converge "
      f"to a tie, because when almost nobody pays unaided everything has uplift and "
      f"ranking by success rate is nearly the same ordering. **The direction does**: "
      f"advantage runs {adv[0]:.2f}× → {adv[-1]:.2f}×, never behind, rising with "
      "self-recovery — which is the Indian case.\n")
    w("\nThis sweep earned its place. An earlier version filtered targets by a hardcoded "
      "taxonomy flag and *lost outright* at low self-recovery, because the rule was right "
      "at one rate and wrong at others. The fix was to delete the rule and let the "
      "estimator decide.\n")

    w("---\n\n## 5. Why the intervals are always-valid\n")
    w(f"ANTAR watches its own effect continuously and pauses arms on it. That is a "
      f"stopping rule, and stopping rules void fixed-horizon statistics. Across "
      f"{peek['n_experiments']} experiments where the true effect is **exactly zero**, "
      f"peeked {peek['peeks_per_experiment']} times each:\n\n"
      f"| Method | False positive rate |\n|---|---:|\n"
      f"| Fixed-horizon, recomputed each peek | **{peek['fixed_horizon_fpr']:.1%}** |\n"
      f"| Always-valid confidence sequence | **{peek['always_valid_fpr']:.1%}** "
      f"(target ≤ {peek['alpha']:.0%}) |\n")
    w(f"\nEvery alarm above is false by construction. The pooled ATE estimate is "
      f"{ate['always_valid']['point']:+.4f} "
      f"[{ate['always_valid']['lower']:+.4f}, {ate['always_valid']['upper']:+.4f}] "
      f"against a ground truth of {ate['truth']:+.4f} the estimator never sees — "
      f"covered: {ate['covered']}.\n")

    w("---\n\n## 6. Silence during an outage\n")
    w(f"| | |\n|---|---:|\n"
      f"| Rail outages simulated | {det['true_outages_in_window']} |\n"
      f"| Above the detection floor | {det['detectable']} |\n"
      f"| Detected | **{det['detected_of_detectable']} of {det['detectable']}**, "
      f"{det['episodes']} episodes, no false positives |\n"
      f"| Transactions inside an open incident | {frz['frozen_transactions']:,} |\n"
      f"| Baseline would contact, inside the incident | "
      f"**{frz['baseline_would_contact_inside_incident']:,}** |\n"
      f"| ANTAR contacts, inside the incident | **{frz['antar_contacts_inside_incident']:,}** |\n")
    w("\nThose messages would tell customers their payment failed during a window when the "
      "bank was down and nothing they could do would have helped. Staying silent is the "
      "correct action, and no success-rate metric will ever reward it.\n")
    w("\nRecall is scored against outages *above the detection floor*. A rail carrying "
      "almost no traffic cannot have an outage detected by any method; scoring against "
      "those would be marking our own homework generously.\n")

    w("---\n\n## 7. What the rules refused, and what stopped itself\n")
    w(f"**Compliance** — {comp['selected']:,} selected, **{comp['delivered']:,} delivered**, "
      f"{comp['veto_total']:,} vetoed:\n\n")
    for rule, n in sorted(comp["vetoes"].items(), key=lambda kv: -kv[1]):
        w(f"- `{rule}` — {n:,}\n")
    w("\nEvery veto is written to the hash-chained ledger with the rule that fired. An "
      "audit trail that only records what happened is half a trail.\n")
    w("\n**Stopping rules** — the trial's safety board:\n\n"
      "| Arm | Effect | 95% CS | State | Reason |\n|---|---:|:---:|---|---|\n")
    for arm in d6["arms"]:
        state = "⏸ paused" if arm["paused"] else "▶ running"
        w(f"| `{arm['arm']}` | {arm['effect']:+.3f} | "
          f"[{arm['lower']:+.3f}, {arm['upper']:+.3f}] | {state} | {arm['reason']} |\n")
    w("\n`A_TRANSIENT_RAIL` pauses itself. That is the cohort the baseline spends most of "
      "its budget on, and ANTAR stops it without being told to.\n")

    w("---\n\n## 8. The P&L, in full\n")
    w("```\n" + d6["pnl_text"]["baseline"].replace("baseline", "NAIVE BASELINE", 1) + "\n```\n")
    w("```\n" + d6["pnl_text"]["antar"].replace("antar", "ANTAR", 1) + "\n```\n")

    w("---\n\n## 9. Read this before quoting a number\n")
    w(f"- **The net-value interval is enormous** — "
      f"[₹{a['ci_low']:,.0f}, ₹{a['ci_high']:,.0f}]. Per-transaction net value runs from a "
      "few rupees of margin to minus a whole customer lifetime, so a time-uniform bound "
      "over that spread is necessarily loose. The defensible claim is the ordering and the "
      "efficiency, not the rupee figure.\n")
    w("- **The magnitudes are simulator-dependent.** They follow from a self-recovery rate "
      "we chose. Section 4 is the answer: the ranking holds across the range, the multiple "
      "does not.\n")
    w("- **Our overstatement ratio is not Yuno's 30–60%.** Theirs measures last-touch "
      "attribution overstating one mechanism inside a multi-mechanism stack. Ours measures "
      "gross versus incremental on a chosen cohort — a larger and different quantity. They "
      "agree qualitatively; quoting one as the other would not survive a knowledgeable "
      "reader.\n")
    w("- **Channels are mocked.** TRAI DLT registration takes weeks. Message *content* is "
      "real, delivery is simulated, costs are fully accounted. Payment plumbing runs "
      "against Razorpay test-mode APIs.\n")

    body = "".join(parts)
    # A "---" on the line immediately after text is a setext heading underline,
    # not a horizontal rule. Guarantee the blank line rather than relying on
    # every call site remembering it.
    body = re.sub(r"(?<!\n)\n---\n", "\n\n---\n", body)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT} ({len(body):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
